name: sick-fits

services:
  - name: backend
    github:
      repo: mitchellhamilton/advanced-react-rerecord
      branch: master
      deploy_on_push: true
    source_dir: finished-files/backend
    routes:
      - path: /backend
    http_port: 8888
    build_command: npm run build
    run_command: npm start
